apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-cron-fail
  namespace: cron-demo
  labels:
    app.kubernetes.io/part-of: argo-notify-cron-demo
spec:
  schedule: "*/3 * * * *"               # 3分おき
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: 120
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: runner
              image: busybox:1.36
              command: ["sh","-c","echo '[NG] cron failed intentionally'; exit 1"]
              resources:
                requests: { cpu: "10m", memory: "16Mi" }
                limits:   { cpu: "100m", memory: "64Mi" }

